NeuroSymbolicAI/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from django.conf import  settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path,include
from home import views

from rest_framework.urlpatterns import  format_suffix_patterns

urlpatterns = [
    path('',views.index,name='index'),
    path('results',views.results,name='results'),
    path('api/v1/post',views.NSAIList.as_view())
]

urlpatterns = format_suffix_patterns(urlpatterns)

home/models.py
import datetime

from django.db import models

# Create your models here.
class NSAI(models.Model):
    photo = models.FileField(upload_to='')
    question = models.CharField(max_length=128)

    def __str__(self):
        return "{}".format(datetime.datetime.now())

home/forms.py
from django import forms


class NSA(forms.Form):
    # imageupload = forms.FileField(label=" Input Image",required= True,widget=forms.FileField(attrs={'class': "form-control", 'placeholder': 'upload image','accept': 'image/*'}))
    photo = forms.FileField(widget=forms.FileInput(
        attrs={'class': "form-control", 'placeholder': 'Student Photo', 'accept': 'image/*'}))
    question = forms.CharField(label="Question",required=True,
                               widget=forms.TextInput(attrs={'class': "form-control", 'placeholder': 'Question'}))

home/views.py
from django.http import JsonResponse
from django.shortcuts import render
from .models import NSAI


from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from .serializers import NSAISerializer
from django.http import Http404



# Create your views here.
def index(request):
    return render(request, 'index.html')

def results(request):

    if request.method == 'POST':
        photo =  request.FILES["photo"]

        question = request.POST["question"]

        NSAI(photo=photo,question=question).save()

        context = {
                       "question": question
        }

        # context = serializers.serialize('json',context)
        print(context)

        return JsonResponse(context)

    print("No cont")

    return render(request, 'index.html')



class NSAIList(APIView):
    """
        Retrieve, update or delete a snippet instance.
        """



    def post(self, request):
        serializer = NSAISerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)



    def delete(self, request, pk, format=None):
        snippet = self.get_object(pk)
        snippet.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)

templates/index.html
{% load static %}
<html>

<head>
    <title>Ask me what you see</title>
     <link rel="icon" href="https://www.flaticon.com/premium-icon/icons/svg/2097/2097960.svg" type="image/gif" sizes="16x16">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
            integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
            integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
            crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'css/mainstyle.css' %}">
    <script src="{% static 'js/mainscript.js' %}"></script>
</head>
<body>
<div class="container">
    <br/>
    <h2 class="display-3 font-weight-bold">What you see is what you get</h2>
    {#         <input type='file' onchange="readURL(this);" />#}

    <form action="" method="post" enctype="multipart/form-data" class="form" id="id_ajax_upload_form">
        {% csrf_token %}
        <p><img id="blah" src="#" alt="."></p>


        <p><label for="id_photo">Photo:</label>
            <input type="file" name="photo" class="form-control" onchange="readURL(this)"
                   placeholder="Student Photo" accept="image/*" required=""
                   id="id_photo"></p>
        <p><label for="id_question">Question:</label>
            <input type="text" name="question" class="form-control"
                   placeholder="Question" required="" id="id_question"></p>

        <p><input type="submit" class="btn btn-outline-primary" value="Submit" ></p>

    </form>
    <br/>
    <span id="msg"></span><br><br>
    <br/>
    <input type="button" class="btn btn-outline-primary" value="Speak" id="speak"/>
    <input type="button" class="btn btn-outline-warning" onclick="pause()" ; value="Pause" id="pause"/>
    <br/><br/>
    <h6 type='text' id="speech-msg">{{ text }}</h6>
</div>

<!-- Footer -->
<footer class="page-footer font-small special-color-dark pt-4">
    <center><h3>Follow and Support me on</h3></center>
    <!-- Footer Elements -->
    <div class="container">

        <!-- Social buttons -->
        <ul class="list-unstyled list-inline text-center">
            <li class="list-inline-item">
                <a class="btn-floating btn-fb mx-1" href="https://www.facebook.com/nitin.sahu.39750">
                    <i class="fa fa-facebook-f fa-2x"> </i>
                </a>
            </li>
            <li class="list-inline-item">
                <a class="btn-floating btn-tw mx-1" href="https://twitter.com/sudoNitin">
                    <i class="fa fa-twitter fa-2x"> </i>
                </a>
            </li>
            <li class="list-inline-item">
                <a class="btn-floating btn-gplus mx-1" href="https://www.youtube.com/channel/UCqfXZHvyiaw3vDWO_lxO7kQ">
                    <i class="fa fa-youtube-play fa-2x"> </i>
                </a>
            </li>
            <li class="list-inline-item">
                <a class="btn-floating btn-li mx-1" href="https://www.linkedin.com/in/nitin-sahu-globefire/">
                    <i class="fa fa-linkedin fa-2x"> </i>
                </a>
            </li>
            <li class="list-inline-item">
                <a class="btn-floating btn-dribbble mx-1" href="https://www.instagram.com/debuggingcode/">
                    <i class="fa fa-instagram fa-2x"> </i>
                </a>
            </li>
            <li class="list-inline-item">
                <a class="btn-floating btn-dribbble mx-1" href="https:github.com/globefire/">
                    <i class="fa fa-github fa-2x"> </i>
                </a>
            </li>
        </ul>
        <!-- Social buttons -->

    </div>
    <!-- Footer Elements -->

    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">© 2020 Copyright:
        <a href="https://github.com/globefire/"> Brian Njoroge</a>
    </div>
    <!-- Copyright -->

</footer>
<!-- Footer -->


</body>
</html>

templates/index2.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
  <link rel="stylesheet" href="{% static 'css/animate.css' %}" />
  <link href="//netdna.bootstrapcdn.com/font-awesome/3.0.2/css/font-awesome.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/forms.css' %}">

</head>

<body>
  <div id="wrapper">
    <div id="uploader">
      <div class="title">
        <h2>UPLOAD FORM</h2>
        <h2><span class="close"><i class="icon-off"></i></span></h2>
      </div>
      <div class="body">
        <div class="dropzone"><i class="icon-cloud-upload"></i> Drop Here</div>
        <div class="list">
          <ul>
            <li><i class="icon-file-alt"></i>index.html <span class="cancel"><i class="icon-minus-sign"></i></span></li>
            <li><i class="icon-file-alt"></i>style.css <span class="cancel"><i class="icon-minus-sign"></i></span></li>
            <li><i class="icon-file-alt"></i>jquery.js <span class="cancel"><i class="icon-minus-sign"></i></span></li>
            <li><i class="icon-file-alt"></i>logo.png <span class="cancel"><i class="icon-minus-sign"></i></span></li>
            <li><i class="icon-file-alt"></i>logo.png <span class="cancel"><i class="icon-minus-sign"></i></span></li>
          </ul>
        </div>
        <div class="progress">
          <div class="bar"></div>
          <div class="tip">50%</div>
        </div>
      </div>
    </div>
  </div>
</body>



</html>